<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-04 at 15:05:42.
 */
class JavascriptFormatterTest extends PHPUnit\Framework\TestCase {
    /**
     * @var JavascriptFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JavascriptFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers openSILEX\handsontablePHP\tools\JavascriptFormatter::prepareJavascriptText
     * @todo   Implement testPrepareJavascriptText().
     */
    public function testPrepareJavascriptText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers openSILEX\handsontablePHP\tools\JavascriptFormatter::preparePHPArrayToJSArray
     * @todo   Implement testPreparePHPArrayToJSArray().
     */
    public function testPreparePHPArrayToJSArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
